version: '3.8'

services:
    nginx:
        build:
            context: .docker/builds/nginx
            args:
                PUID: $DOCKER_PUID
                PGID: $DOCKER_PGID
        volumes:
            - ./:/var/www/app
            - .docker/data/logs/nginx:/var/log/nginx
        ports:
            - $DOCKER_NGINX_PORT:80

    php:
        build:
            context: .docker/builds/php
            args:
                PUID: $DOCKER_PUID
                PGID: $DOCKER_PGID
        volumes:
            - ./:/var/www/app
        working_dir: /var/www/app
        ports:
            - $DOCKER_PHP_PORT:9000
        environment:
            DB_DATABASE: $MYSQL_DATABASE
            DB_USERNAME: $MYSQL_USERNAME
            DB_PASSWORD: $MYSQL_PASSWORD
            APP_SECRET: $APP_SECRET

    mysql:
        build:
            context: .docker/builds/mysql
        command: "--sql_mode='NO_ENGINE_SUBSTITUTION' --default-authentication-plugin=mysql_native_password --sort_buffer_size=1073741824"
        volumes:
            - .docker/data/mysql:/var/lib/mysql
            - .docker/builds/mysql:/etc/mysql/conf.d
        ports:
            - $DOCKER_MYSQL_HOST_PORT:3306
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USERNAME: $MYSQL_USERNAME
            MYSQL_PASSWORD: $MYSQL_PASSWORD

    redis:
        image: redis:latest
        ports:
            - $DOCKER_REDIS_HOST_PORT:6379

    mailhog:
        restart: always
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - $DOCKER_MAILHOG_SMTP_HOST_PORT:1025
            - $DOCKER_HTTP_HOST_PORT:8025

networks:
    app_network:
